version: '2'

services:

  webserver:
    build: .
    ports: 
      - '80:80'
    volumes:
      - ./myapp:/var/www/html/

  mysql:
    image: mysql:5.7
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql/
    environment: 
      - MYSQL_ROOT_PASSWORD=root_pwd
      - MYSQL_DATABASE=devdb
      - MYSQL_USER=devdb_user
      - MYSQL_PASSWORD=devdb_pwd
